#!/bin/bash
wget https://github.com/WebGoat/WebGoat/releases/download/v8.0.0.M25/webgoat-server-8.0.0.M25.jar
cd Downloads
java -jar webgoat-server-8.0.0.M25.jar [--server.port=8080] [--server.address=localhost]


